version: "3.1"

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=johannes.jahn@outlook.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d/server.conf:/etc/nginx/user_conf.d/server.conf
      - ./static:/home/app/web/